version: '2'

services:
  postgres_cobweb:
    image: postgres
    restart: always
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: cobweb
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"